version: "3.8"

services:
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/wallets_db
      LIQUIBASE_USERNAME: dev
      LIQUIBASE_PASSWORD: admin
      LIQUIBASE_CHANGELOG_FILE: /liquibase/changelog/db.changelog-master.xml
    volumes:
      - ./changelog:/liquibase/changelog
    depends_on:
      - postgres
    command: ["update"]
    networks:
      - net_shared

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallets_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./deploy/init.sql:/docker-entrypoint-initdb.d/init-database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - net_shared
  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4:7.2
    command: -c 'max_connections=1000' -c 'shared_buffers=2GB' -c 'work_mem=524MB' -c 'maintenance_work_mem=256MB' -c 'effective_cache_size=2GB' -c 'max_worker_processes=10' 
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - net_shared

  fastapi:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fastapi_app
    ports:
      - "8080:8080"   # FastAPI default port
    environment:
      MODE: DEV
      DB: postgresql+asyncpg
      DB_USER: dev
      DB_PASS: admin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: wallets_db
      #DATABASE_URL: postgresql://myuser:mypassword@postgres_db/mydatabase
    depends_on:
      - postgres
    networks:
      - net_shared
  locust:
    container_name: locust
    image: locustio/locust
    ports:
      - "8089:8089" 
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py  -H http://fastapi:8080
    networks:
      - net_shared

volumes:
  pgdata:
  pgadmin-data:

networks:
  net_shared: